{
    'name': 'Custom SMS Gateway',
    'version': '1.0.0',
    'category': 'Tools',
    'summary': 'SMS Gateway Configuration for Odoo v19',
    'description': """This module helps to configure custom SMS gateway for Odoo v19""",
    'author': 'Mirinfo Systems Limited',
    'company': 'Mirinfo Systems Limited',
    'maintainer': 'Mirinfo Systems Limited',
    'website': 'http://www.mirinfo-systems.com',
    'depends': ['sms'],
    'data': [
        "security/ir.model.access.csv",
        "views/custom_sms_template.xml",
        "views/sms_mail_sender.xml",
        "views/sms_mail_server.xml",
        "views/sms_outbox_details_views.xml",
        "views/sms_scheduler_data.xml",
        "views/inherited_res_partner_inherit_sms_gateway_custom_views.xml",
        "wizards/send_sms_to_partner_wizard_views.xml",
        "views/menu_views.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    "license": "LGPL-3",
}
