{
    "name": "Custom Target Management",
    "version": "1.0.0",
    "category": "Custom",
    "author": "Mirinfo Systems Limited",
    "company": "Mirinfo Systems Limited",
    "maintainer": "Mirinfo Systems Limited",
    "website": "http://www.mirinfo-systems.com",
    "license": "LGPL-3",
    "sequence": 5,
    "summary": "Custom Target Management",
    "depends": [
        "base",
        "sale",
        "custom_product",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/curstom_target_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}